apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-deployment
  namespace: interview-namespace
  labels:
    app: py-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-flask
  template:
    metadata:
      labels:
        app: py-flask
    spec:
      containers:
      - name: py-flask
        image: 608157257865.dkr.ecr.us-east-1.amazonaws.com/testapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional 
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 8080 
#        readinessProbe:
#          tcpSocket:
#            port: 8080
#          initialDelaySeconds: 5
#          periodSeconds: 10                   
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
