apiVersion: v1
kind: Service
metadata:
  name: interview-service
  namespace: interview-namespace
spec:
  selector:
    app: py-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer