apiVersion: v1
kind: Service
metadata:
  name: interview-service
  namespace: interview-namespace
spec:
  selector:
    app: py-flask
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
  type: {{ .Values.service.type }}